### ISSUE TITLE
Create a "legal" page with terms of service and privacy policy

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/una-hora#2]
Design must basically match the current site.

- [x] Define route
- [x] Define view
- [x] Create template
- [x] Create HTML/CSS for template

Please use the terms of service and privacy policy from the [current website](https://1hora.org/en/legal/).

**Comment by glortiz** [comment]
https://docs.google.com/document/d/1S2yVZ97byp3JgIV73u680OHKiJn1g0hVyWgR-rB03RQ/edit#

Aquí el draft que se trabajó - inglés y español

**Comment by rperezdiaz** [comment]
> https://docs.google.com/document/d/1S2yVZ97byp3JgIV73u680OHKiJn1g0hVyWgR-rB03RQ/edit#
> 
> Aquí el draft que se trabajó - inglés y español

Para incluirlo en legal? @glortiz @rnegron
