### ISSUE TITLE
Add Email / Password Authentication

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/una-hora#4]
- [x] User must be able to sign up using email and password
- [x] User must be able to log in using email and password
- [x] Authenticated user must be able to see protected page
- [x] Unanthenticated used must not be allowed to see a protected page

**Comment by krismuniz** [comment]
I believe I am very close re:Auth but I'm having problems with Tailwind JIT + Docker. I update a template's tailwind classes and it reloads the browser but it doesn't seem to be re-building the tailwind styles. 

Anyone else seen this?

cc @rnegron

**Comment by gcollazo** [comment]
@krismuniz veo que creaste el PR. ¿Lograste resolver o sigues teniendo problemas? En todo caso el que nos puede ayudar con ese setup es @rnegron.

**Comment by krismuniz** [comment]
Lo que hice fue que corrí el proceso de Tailwind en el container usando el CLI. Parece que de la manera que está configurado browsersync responde a cambios pero Tailwind no
